@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "DIG HERE.$"

SealedChamber_InnerRoom_Braille_RedEmerald:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "SEVEN COLORS.\n"
	.braille "RED HIDES BELOW\n"
	.braille "PETALBURG WOODS.\n"
	.braille "BRING THEM ALL.$"

SealedChamber_InnerRoom_Braille_BlueEmerald:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "BLUE RESTS\n"
	.braille "ON THE GRANITE\n"
	.braille "BEACH.$"

SealedChamber_InnerRoom_Braille_GreenEmerald:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "GREEN HIDES\n"
	.braille "IN THE DESERT.$"

SealedChamber_InnerRoom_Braille_YellowEmerald:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "YELLOW LIES\n"
	.braille "ON THE ROAD\n"
	.braille "TO METEOR FALLS.$"

SealedChamber_InnerRoom_Braille_PurpleEmerald:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "PURPLE WAITS\n"
	.braille "BELOW FIELDS\n"
	.braille "OF FLOWERS.$"

SealedChamber_InnerRoom_Braille_WhiteEmerald:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "WHITE SHINES\n"
	.braille "ON THE MOUNTAIN\n"
	.braille "WHERE THE DEAD REST.$"

SealedChamber_InnerRoom_Braille_BlackEmerald:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "BLACK RESTS\n"
	.braille "AT THE START\n"
	.braille "OF THE RIVER.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "LEFT, LEFT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "STAY CLOSE\n"
	.braille "TO THE WALL.\n"
	.braille "RUN AROUND\n"
	.braille "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THOSE WHO\n"
	.braille "INHERIT OUR\n"
	.braille "WILL, SHINE\n"
	.braille "IN THE MIDDLE.$"

@ FRLG
Braille_Text_Up::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "UP$"

Braille_Text_Down::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "DOWN$"

Braille_Text_Right::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "RIGHT$"

Braille_Text_Left::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "LEFT$"

Braille_Text_Cut::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CUT$"

Braille_Text_ABC::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ABC$"

Braille_Text_GHI::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "GHI$"

Braille_Text_MNO::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "MNO$"

Braille_Text_TUV::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "TUV$"

Braille_Text_DEF::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "DEF$"

Braille_Text_JKL::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "JKL$"

Braille_Text_PQRS::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "PQRS$"

Braille_Text_WXYZ::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "WXYZ$"

Braille_Text_Period::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille ".$"

Braille_Text_Comma::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille ",$"

Braille_Text_Everything::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "EVERYTHING$"

Braille_Text_HasMeaning1::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "HAS MEANING$"

Braille_Text_Existence::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "HAS MEANING$"

Braille_Text_BeingAlive::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "BEING ALIVE$"

Braille_Text_HasMeaning3::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "HAS MEANING$"

Braille_Text_HaveDreams::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "HAVE DREAMS$"

Braille_Text_UsePower::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "USE POWER.$"

Braille_Text_LetTheTwo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "LET THE TWO$"

Braille_Text_Glittering::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "GLITTERING$"

Braille_Text_Stones::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "STONES$"

Braille_Text_OneInRed::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ONE IN RED$"

Braille_Text_OneInBlue::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ONE IN BLUE$"

Braille_Text_ConnectThe::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CONNECT THE$"

Braille_Text_Past::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "PAST.$"

Braille_Text_TwoFriends::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "TWO FRIENDS$"

Braille_Text_Sharing::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "SHARING$"

Braille_Text_PowerOpen::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "POWER OPEN$"

Braille_Text_AWindowTo::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "A WINDOW TO$"

Braille_Text_ANewWorld::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "A NEW WORLD$"

Braille_Text_ThatGlows::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THAT GLOWS.$"

Braille_Text_TheNext::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THE NEXT$"

Braille_Text_WorldWaits::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "WORLD WAITS$"

Braille_Text_ForYou::
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "FOR YOU.$"
